### PR TITLE
#90: implement create pos/neg manager tasks

### LINKED ISSUE #90: Task 063. Tests – Manager. Task. Create

### PR DESCRIPTION
**Pull request by JSnow11**
## related
- closes #90 

## implemented
- create positive tests
- create negative tests

## concerns
- positive tests are only going to pass correctly for the first time run after populate sample

### CODE REVIEW

**Comment by JSnow11** [comment]
## fix populate dependency
- now the populate scripts are run before all the tests

**Comment by nicolasdeory** [comment]
> * positive tests are only going to pass correctly for the first time run after populate sample

Will create an extension class to populate sample once for all tests

**Comment by nicolasdeory** [comment]
> ## fix populate dependency
> * now the populate scripts are run before all the tests

Will create an extension so the populate script runs before all test classes

**Review by nicolasdeory — CHANGES_REQUESTED** [review]
Tests seem to be behaving erratically, sometimes reporting as "passed" and other times as "failed".

image

image


I'll try to make a unified population extension because it seems to throw errors from time to time, such as these:

image

image

**Comment by JSnow11** [comment]
## Fix
- all the tests passing fine for me

## Concerns
- creating tasks with Lola21 could also break the positive test check since the task list order may differ

**Review by JSnow11 — COMMENTED** [review]
new changes on the pr

**Comment by nicolasdeory** [comment]
Looks good. I added sleep and disabled autopausing to make them pass in my machine. Merging

**Review by nicolasdeory — APPROVED** [review]

**Pull request merged**
